events {
    worker_connections 1024;
}

http {
    upstream file_storage {
        server file_storage:8080 max_fails=0;
    }

    upstream work_main_api {
        server work_main_api:8080 max_fails=0;
    }

    server {
        listen 8080;

        location ~ "^/works/[^/]+/download$" {
            proxy_pass http://file_storage;
        }

        location /works {
            proxy_pass http://work_main_api;
        }
    }
}
